listen_addresses = '*'

max_connections = 200

shared_buffers = 180GB
effective_cache_size = 160GB
maintenance_work_mem = 16GB
work_mem = 256MB
wal_buffers = 64MB

max_worker_processes = 32
max_parallel_workers_per_gather = 4
max_parallel_workers = 32

max_wal_size = 16GB
checkpoint_timeout = 15min
