services:
  postgresql_server:
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql_server
    image: ankane/pgvector:latest
    restart: always
    volumes:
      - ../db/postgresql:/var/lib/postgresql/data
      - ./config/pgvector_extension.sql:/docker-entrypoint-initdb.d/init-vector_extension.sql
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - local_pubmed_network

  pgbouncer:
    container_name: ${COMPOSE_PROJECT_NAME}-pgbouncer
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      # 连接配置
      DB_HOST: postgresql_server
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      # 连接池策略
      POOL_MODE: transaction  # 推荐使用事务模式，性能最高
      MAX_CLIENT_CONN: 1000   # 允许应用连接数
      DEFAULT_POOL_SIZE: 20   # 维持与后端 Postgres 的连接数（通常 20-50 足够）
    volumes:
      - ./config/userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - local_pubmed_network
    depends_on:
      - postgresql_server

  redis_server:
    container_name: ${COMPOSE_PROJECT_NAME}-redis_server
    image: redis:alpine
    restart: always
    volumes:
      - ../db/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --dir /data
    networks:
      - local_pubmed_network

  django_backend:
    container_name: ${COMPOSE_PROJECT_NAME}-django_backend
    image: novoagi-backend:latest
    restart: always
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - ../local_pubmed/backend:/app/backend
      - ../db/django:/app/backend/data
      - ../logs:/app/logs
      - ./config:/app/config
      - ./django.env:/app/backend/.env
    environment:
      DJANGO_ADMIN_USERNAME: ${DJANGO_ADMIN_USERNAME}
      DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
    depends_on:
      - postgresql_server
      - redis_server
      - pgbouncer
    networks:
      - local_pubmed_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  local_pubmed_network:
    external: true
    name: local_pubmed_network
