# Generated by Django 5.2.8 on 2025-11-19 17:05

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubmedArticle',
            fields=[
                ('pmid', models.IntegerField(primary_key=True, serialize=False, verbose_name='PMID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('journal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Journal')),
                ('med_abbr', models.CharField(blank=True, max_length=500, null=True, verbose_name='Med Abbreviation')),
                ('iso_abbr', models.CharField(blank=True, max_length=500, null=True, verbose_name='ISO Abbreviation')),
                ('pubdate', models.CharField(blank=True, max_length=500, null=True, verbose_name='Publication Date')),
                ('pubmed_pubdate', models.DateField(blank=True, null=True, verbose_name='Pubmed Publication Date')),
                ('pmc', models.CharField(blank=True, max_length=500, null=True, verbose_name='PMC')),
                ('issn', models.CharField(blank=True, max_length=500, null=True, verbose_name='ISSN')),
                ('e_issn', models.CharField(blank=True, max_length=500, null=True, verbose_name='E-ISSN')),
                ('doi', models.CharField(blank=True, max_length=500, null=True, verbose_name='DOI')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('pagination', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pagination')),
                ('volume', models.CharField(blank=True, max_length=500, null=True, verbose_name='Volume')),
                ('issue', models.CharField(blank=True, max_length=500, null=True, verbose_name='Issue')),
                ('pub_status', models.CharField(blank=True, max_length=500, null=True, verbose_name='Publication Status')),
                ('authors', models.JSONField(blank=True, null=True, verbose_name='Authors')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='Keywords')),
                ('pub_types', models.JSONField(blank=True, null=True, verbose_name='Publication Types')),
                ('author_mail', models.JSONField(blank=True, null=True, verbose_name='Author Mails')),
                ('author_first', models.CharField(blank=True, max_length=500, null=True, verbose_name='Author First')),
                ('author_last', models.CharField(blank=True, max_length=500, null=True, verbose_name='Author Last')),
                ('affiliations', models.JSONField(blank=True, null=True, verbose_name='Affiliations')),
                ('impact_factor', models.FloatField(blank=True, null=True, verbose_name='Impact Factor')),
                ('abstract_cn', models.TextField(blank=True, null=True, verbose_name='Abstract CN')),
                ('title_abstract_vector', pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Title Abstract Vector')),
            ],
            options={
                'verbose_name': 'Pubmed Article',
                'verbose_name_plural': 'Pubmed Articles',
                'db_table': 'pubmed_articles',
                'ordering': ['-pubmed_pubdate'],
            },
        ),
    ]
