# Generated by Django 5.2.8 on 2025-11-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticle',
            name='factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor'),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='jcr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='JCR'),
        ),
    ]
