# Generated by Django 5.2.8 on 2025-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0002_pubmedarticle_factor_pubmedarticle_jcr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubmedarticle',
            name='impact_factor',
        ),
    ]
