# Generated by Django 5.2.8 on 2025-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0003_remove_pubmedarticle_impact_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticle',
            name='zky',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZKY'),
        ),
    ]
