# Generated by Django 5.2.8 on 2025-12-01 15:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0004_pubmedarticle_ts_en_pubmedarticle_zky'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticle',
            name='ts_en',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
