# Generated by Django 4.2.5 on 2026-03-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0005_pubmedarticle_ts_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pubmedarticle',
            options={'managed': False, 'verbose_name': 'Pubmed Article', 'verbose_name_plural': 'Pubmed Articles'},
        ),
    ]
