# Generated by Django 4.2.5 on 2026-04-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0006_alter_pubmedarticle_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pubmedarticle',
            table='pubmed_articles_2',
        ),
    ]
