# Generated by Django 5.2.8 on 2026-05-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubmed', '0007_alter_pubmedarticle_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMCArticle',
            fields=[
                ('pmcid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='PMCID')),
                ('body', models.JSONField(blank=True, null=True, verbose_name='Body')),
                ('pubmed', models.OneToOneField(blank=True, db_column='pmid', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmc_article', to='pubmed.pubmedarticle', verbose_name='Pubmed')),
            ],
        ),
    ]
